### ISSUE TITLE
Show password strenght hints while typing

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#21]
In dashboard, on password picking page ( https://dashboard.blindnet.io/verify-user?token=7991278a-8ccd-48d2-b540-a5c1c69c152c ) the user can type a short, not acceptable password, and discover it is bad only when clicking on the "confirm password" button. To complement this catastrophic workflow, if the user enetered an innacceptable password, and also did not confirm the terms and conditions, the system first only tells him to accept the terms and conditions and define a password. Then, once the user accepts them, and only then, he learns that the password is not strong enough!

The current workflow is the example of everything this company stands against in terms of interaction design!

**What should be done**

- As soon as the user starts typing, show in the right panel a notification about what is the required password cacacteristics. 
- Highlight the caracteristics that the current password does not yet fulfill
- Change highlight as the user improves the password. 
- Once acceptable, present a nice OK sign and inform the user how difficult it is to guess that password (how many years it would take the supercomputer)
- Ideally instead of saying "password MUST contain..." say "Password is not strong enough. A chield can guess it in 1 hour" or "A comodore computer can guess it in 0.8 days"...

**The problem should be also fixed in other contexts where it appears**
- On passowrd change (no indication is given while typing that the new passowrd is not good enough)
https://dashboard.blindnet.io/change-password
<img width="581" alt="Untitled" src="https://user-images.githubusercontent.com/317424/127674793-83156966-4bbb-41c0-b30c-03efbdf6132b.png">

**Why**

- Because blindnet is a user-centric company

**Technical context:**
Firefox 90.0.2 (64-bit)
on MacOS Catalina 10.15.7
MacBook Pro (13-inch, 2017)
2560 x 1600

**Comment by Clementinev** [comment]
It works but there are few thing to fix: 
1. can it be more reactive ? Can the right panel message appear right away when user clicks in new password field, and can validation for each condition be faster e.g as soon as user types a character ? 
![Kapture 2022-10-13 at 14 41 11](https://user-images.githubusercontent.com/89908145/195600780-17665eb6-caf2-4f16-bbd0-e9e9f7f38a1a.gif)
2. when user clicks elsewhere than in new password field, right panel message with conditions should disappear 
3. on modify account page, can we have validation for new password field, with red validation message under the field (as for log in page) if something as been typed in the field (no validation if nothing typed in because user might just have changed their name) ?
