### ISSUE TITLE
Challenge Approve/Reject button design for lower probability of error

### ISSUE THREAD

**Issue by milstan** [blindnet-io/product-management#625]
In the Rights Request approval process, we have two clearly distinct buttons for approval and rejection, that appear on the bottom of the page.
![image](https://user-images.githubusercontent.com/317424/168556758-04eb595e-4693-4e27-a667-773f0466cc52.png)

This seems natural. However, when I am using the form, if I am distracted, I may still get confused. When I am rejecting the form, I am drown by the green color, as I want to have my rejection decision sent. It's only by reading the button labels that I can avoid clicking on the wrong button (accept when I want to reject).

I suggest we challenge this desing and see if a desing where the Approve/Reject decision would be made by using a (required) radio-button to clearly choose one of the two options (Approve/Reject), and then have the button only serve for "Send"

Such button would only get active once all the reuqired fields are filled-in.

**Comment by Clementinev** [comment]
Validation message should be kept as in old design when user tried to hit send button when rejecting without adding the justification message : 
- Currently on **access request** no validation message when I try to hit send without adding message **-> there should be validation message when user tries to hit send when reject without message** : <img width="1440" alt="Screenshot 2022-10-17 at 16 46 01" src="https://user-images.githubusercontent.com/89908145/196209494-266fbffa-7eb3-4a99-9d08-3c818ad9f5f1.png">
Old design : <img width="1438" alt="Screenshot 2022-10-17 at 16 47 13" src="https://user-images.githubusercontent.com/89908145/196209499-9564429c-24b9-46cb-b2c0-9f4edd50b63e.png">
- on **delete request** the validation message appears only after I clicked in the message field otherwise it doesn't appear if I directly try to hit send button without previously clicking in the message field for **partially approve** and **reject** **-> there should be validation message when user tries to hit send when reject without message without previously clicking in the field**
