### ISSUE TITLE
Change upload multiple files buttons style and workflow

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/product-management#667]
Currently when uploading multiple files, the workflow and buttons are confusing and could better convey that the user can add multiple files : 
- The wording on the green "+" button is the same in english and french, and doesn't convey the possibility of adding multiple files
- fields style is the same when waiting for uploaded document and when document is uploaded
- When user adds the first document, it is not straight forward that he can add another one if he doesn't click again on the "+" button 
<img width="200" alt="Screenshot 2022-06-01 at 11 25 30" src="https://user-images.githubusercontent.com/89908145/171372886-aa52ecb7-9803-4085-95df-a908945a2d3c.png"> -> <img width="200" alt="Screenshot 2022-06-01 at 11 25 39" src="https://user-images.githubusercontent.com/89908145/171372882-66f92949-d13b-4d76-9726-44bc22d48504.png"> -> <img width="200" alt="Screenshot 2022-06-01 at 11 25 48" src="https://user-images.githubusercontent.com/89908145/171372879-ae15cca1-9f53-40ed-8574-0fc1b0050388.png">

**What could be done :** 
Change workflow and buttons style such as in the sketches below : 
- Having different button/field style for when document is yet to be uploaded and when document has been uploaded
- Having the bin icon only when a document has been updated
- Using the dashed border only on button/field to convey that a document is yet to be uploaded, and empty/white background
- Changing wording to FR:"Ajouter un document" / EN: "Add a file" and have the font in italic

<img width="200" alt="Screenshot 2022-06-01 at 11 30 11" src="https://user-images.githubusercontent.com/89908145/171373519-db0cda59-da1c-4f17-b7a2-fddd41ca3b9a.png"> document added-><img width="200" alt="Screenshot 2022-06-01 at 11 30 22" src="https://user-images.githubusercontent.com/89908145/171373508-47f1bac1-96a9-4caf-af47-7c3e716e7060.png">

What do you think ? If it is too much development, I suggest to change the wording of the green "+" button to FR: "Ajouter un document" / EN: "Add a document" so it conveys that you can add several documents

**Comment by m4rk055** [comment]
I like the proposed workflow.
Green button opens the file picker, right?

(When a file is selected, display the next **Add file box** right away)

> Having different button/field style for when document is yet to be uploaded and when document has been uploaded

Files are actually uploaded after the submit button is clicked (GDPR page). So there is just one state - document added.

> I suggest to change the wording of the green "+" button to FR: "Ajouter un document" / EN: "Add a document" so it conveys that you can add several documents

**Upload file** is indeed a wrong label.
This should be done immediately. Can you create a new issue?

**Comment by Clementinev** [comment]
> Green button opens the file picker, right?
Yes : Add a document and green button opens file picker

> Files are actually uploaded after the submit button is clicked (GDPR page). So there is just one state - document added.
I meant having different button/field style for when no file has been added (the "Add a document field/button) and when a file has been added (the file field)

> Can you create a new issue?
Yes I'll create a new issue

**Comment by filipblnt** [comment]
I like the idea for the new workflow, and I think it could be even better by reducing possibilities to do one thing in several ways.

For example, I think it's confusing to add a new file both with clicking the green button and with clicking on file field, like now (image below). I think the original idea was for the green button to add new file field.
<img width="200" alt="Screenshot 2022-06-01 at 11 30 11" src="https://user-images.githubusercontent.com/89908145/171373519-db0cda59-da1c-4f17-b7a2-fddd41ca3b9a.png">

How about this (I think it's the same workflow as proposed only without the green button:

- One field at the beginning with the text saying "Add your file(s)" / "Ajouter le(s) document(s)" -> conveying a message that a submitter must click the field in order to add one or multiple files. But no trash icon and no green button here. And as soon as the field is clicked, a dialog box opens.
      <img width="200" alt="1" src="https://user-images.githubusercontent.com/73657349/171743702-989cd302-9796-4f64-9798-627022876224.png">


- When a submitter selects one or many files, these are listed with trash icons, and a new field is added at the bottom with the similar text as at the beginning  "Add more files" / "Ajouter autres documents". Again, no green button next to this field.
      <img width="200" alt="2" src="https://user-images.githubusercontent.com/73657349/171743737-fae70cd5-30e4-4cec-b37f-a4a7d6bf8d38.png">

**Comment by Clementinev** [comment]
Yes I agree, and I was thinking how about this sketch below, so we keep the visual of the + green button (which convey clearly information of adding a doc) : 
<img width="200" alt="Screenshot 2022-06-03 at 10 09 29" src="https://user-images.githubusercontent.com/89908145/171815149-e326b9aa-600e-4bb8-853a-0a0dae524f77.png"> -> add doc -><img width="200" alt="Screenshot 2022-06-03 at 10 09 36" src="https://user-images.githubusercontent.com/89908145/171815165-8f51b473-58c9-432e-831e-bd1fee8a1222.png">

**Comment by Clementinev** [comment]
Works well
