### ISSUE TITLE
Complete Privacy Computation Engine model

### ISSUE THREAD

**Issue by m4rk055** [blindnet-io/product-management#725]
Model based on [PRIV document](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md) was already created in the PR https://github.com/blindnet-io/product-management/pull/724.
[Expected behaviour document](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/expected-behavior.md) introduces new concepts and relationships that need to be included in the model.

**Comment by milstan** [comment]
I changed the name according to [HLC](https://github.com/blindnet-io/product-management/blob/main/refs/high-level-architecture/readme.md#privacy-computation-engine). See also [this comment](https://github.com/blindnet-io/product-management/pull/723#issuecomment-1164143268).

Just a reminder that Privacy Computation Engine SHOULD be able to take, as input, a variety of settings, as described in:
- [Implications for Systems Implementing PRIV](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/RFC-PRIV.md#storing-general-information)
- [Expected Behavior / Configuration](https://github.com/blindnet-io/product-management/blob/devkit-schemas/refs/schemas/priv/expected-behavior.md#configuration-and-prerequisites)

We MAY want to support UROPA format, i.e. Privacy Computation Engine MAY be fed this data using [UROPA](https://github.com/uropa-project/uropa) format.

In addition, the general settings data from this model, [consitute a record of processing activity (under Article 30 of GDPR), and as such might need to be exported and shown.](https://gdpr-info.eu/art-30-gdpr/)
