### ISSUE TITLE
[Epic] update the DevKit v0 architecture

### ISSUE THREAD

**Issue by m4rk055** [blindnet-io/product-management#760]
Synthesize all updates of the DevKit v0 architecture as discussed during the previous week.

## Goal

All refs should be up to date before 2022-07-07.

> **Warning**
>
> This goal can only be achieved once we have all mastered the **Antiperfectionism principle**: _(Good-enough, finished) is prefered over (Potentially perfect, in progress)._

## Sub-tasks

> To be updated step-by-step

- [x] #761
- [x] #748 
- [x] #751 
- [x] #659 
- [x] #723 
- [x] #754
- [x] #773

**Comment by noelmace** [comment]
Here, @m4rk055 acts as the technical leader: he is responsible for tracking all updates and making sure no information is missing or unclarified before July 7th, which is why he is the only assignee.

**ALL** @blindnet-io/engineering, including @m4rk055 and @noelmace, are responsible for helping him achieve this goal.
