### ISSUE TITLE
Implement Privacy compiler business logic and models

### ISSUE THREAD

**Issue by m4rk055** [blindnet-io/product-management#775]
Define objects and interfaces according to [PRIV](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/RFC-PRIV.md) and implement [expected behavior](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/expected-behavior.md).
Create a database [model](https://github.com/blindnet-io/product-management/tree/main/specifications/model).

**Comment by milstan** [comment]
After working on the Multicast Protocol I think the key of the work here is to have a very smart way to approach the data structure that will store the PRIV objects.

The same structure can serve both the Privacy Computation Engine and the Multicast Protocol, as both need to know the history of PRIV objects related to one Data Subject.

The order in which PRIV objects are processed is important. Ideally, Privacy Compiler shoudl read a hisotry of PRIV objects, recalucate Privacy Scopes, and deliver its recommendations.

Privacy Compiler should work with the history it knows. This history can be updated (non-sequentally), and then the Privacy Compiler recalucates if needed. Menaing the same Data Subject can get different responses with regards to the state of history known to the Privacy Compiler.

I also intend to [add Events](https://github.com/blindnet-io/product-management/issues/798) as objects to PRIV (so that everything that is stroed in this data structure) can be said to be a PRIV object.

**Comment by milstan** [comment]
@m4rk055 please note that PCE and PC MUST work regardless of the client System implementing other components.

The following edge-case situations MIGHT happen:
- the Client System only implements PRCI to capture Privacy Reqeusts. It gives general configuration to PCE. The client uses NECESSARY legal base for certain data categories. The PC/PCE are not given any knowledge of any PRIV event concerning a particular user. The following requests are automated:
    - Transparency (non logged user)
    - DELETE requests automatically rejected for Data Categories under necessary.
    - Recommend to GRANT ACCESS request if user is authenticated (even thos this access has to happen somewhere else, not linked to blindnet devkit)
PCE can still make some recommendations, but for most Privacy Request it has nothing to recommend.

- the Client System can (in addition to configuration) send PRIV events (Legal Base Events, Consents) but not implement Data Access Component. PCE can automate certain reponses, make recommendations for certain requests. It can recommend to accept ACCESS, MODIFY requests (even if the actual operation on data has to happen somewhere else or be done manually). It can recommend to reject certain DELETE requests.

- The client System can (in addition to configuration, and PRVI events) also implement Storage or Data Access Component. A much more complete service can be offered by blindnet devkit then.
