### ISSUE TITLE
Evaluate Biscuit

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#863]
## Context

We plan to start adding authentication in v0.4 (see https://github.com/blindnet-io/product-management/issues/721#issuecomment-1193139007).

## What to do

Quickly evaluate:

1. how Biscuit could be used in the DevKit
    - keep in mind that right now, implementations of Biscuit v2 are only provided in Rust, Web Assembly and Haskell
    - would you think we'd need an implementation in Java, or even Scala for that, or just create a dedicated component in Rust / Haskell?
2. intersections between PRIV and Biscuit (might be linked to https://github.com/blindnet-io/product-management/issues/840)
3. how we could help Biscuit development in the future as part of our development **if** we decide to use it, especially ([from their README](https://github.com/biscuit-auth/biscuit#how-to-help-us)):
    1. **provide use cases** that they can test the token on (some specific kind of caveats, auth delegation, etc)
    2. add support for biscuit v2 to java and go implementations
    3. cryptographic design audit: they need reviews of algorithms, their usage and implementation in various languages
    
## Ressources

- https://www.clever-cloud.com/blog/engineering/2021/04/12/introduction-to-biscuit/
- https://www.clever-cloud.com/blog/engineering/2021/04/15/biscuit-tutorial/
- https://github.com/biscuit-auth/biscuit
- https://www.biscuitsec.org/
- https://matrix.to/#/#biscuit-auth:matrix.org

**Comment by milstan** [comment]
I had a look at biscuit and it does seem as a solid way to approach a global problem. 

I am not sure that this qualifies it for us to use it.

These are the requirements four our authentication in blindnet devkit:
- there is a war going on over the dominant user identity (and authentication) tool on the web. Blindnet MUST NOT take any sides in that war.
- Blindnet MUST NOT constrain its clients to use any particular user identity / authentication schema, and MUST be compatible with as many as possible. 
- a System implementing blindnet devkit can't be expected to change the way they do user identity and authentication in order to implement blindnet devkit
- it MUST be possible to authenticate the same user is several different ways across several components. For example a user can have an account on the system, use it to provide data, but then when they submit a Privacy Request we might authenticate them, not using that account, but using magiclink or with scan of ID.

The question of what authentication to support first, is really a question for @TheKinrar @jboileau99 and @m4rk055 . Maybe that is biscuit? I don't know. My intuition is no.

We are likely to have first Systems to implement DevKit implement PRCI in a very distributed context. Those first Systems are likely to be applications of external DPOs. They don't have any data on the user in their system.
- they will only use PRCI to authenticate the user and capture the request
- they will use PCE for recommendations that they can get
- their clients (distinct systems) can implement blindnet devkit data access component, and send PRIV events to PCE (to allow better automation)

They might want to use different authentication in those two contexts - one in the External DPO's software implementing PRCI and another in the client's software implementing Data Access Component.

IMHO, this favors the following authentication for PRCI (as fist to be supported):
- magic link and
- identification over submitted ID document (either ours, as done in privateform, or a third-party service allowing this)

What do other think?

**Comment by noelmace** [comment]
FYI, I'm mostly asking this to help me find a starting point to (1) discuss PRIV and the DevKit with CleverCloud, (2) purpose them to join the OpenPrivacy initiative and (3) help build early engagement.

Biscuit is trending, but not mature and popular enough to be considered a priority when it comes to authentication/autorisation IMHO, except, of course, if @blindnet-io/engineering consider it solves several problems and it's therefore the best option technically wise.

I already have many other options for (1).

Finding links between Biscuit and PRIV seemed to me liked a good option for (2), but I'm open to suggestions (in a dedicated issue in communication-management).

This isn't a high priority, don't spend too much time discussing this.

**Comment by milstan** [comment]
I am closing this as clearly the team has no time to do any further evaluation at this point.
